#!/usr/bin/env python
"""
    setup.py
    ~~~~~~~~

    :copyright: (c) 2013 by Ryan Olson.
    :license: BSD, see LICENSE for more details.
"""

from setuptools import setup, find_packages

setup(
    name='clapp',
    version='0.1dev',
    packages=find_packages(exclude=["dependencies", "sample"]),
    zip_safe=False,
    include_package_data=True,
    platforms='any',
    setup_requires=[
        'setuptools>=0.8',
    ],
    install_requires=[
        'Fabric',
        'Flask',
        'Flask-Babel',
        'Flask-Bootstrap>=2.3.2.12',
        'Flask-CouchDB-Schematics>=0.1.0-beta',
        'Flask-Login',
        'Flask-Principal',
        'Flask-Script',
        'Flask-WTF',
        'Flower',
        'celery-with-redis',
        'authomatic',
        'gunicorn',
        'pygments',
        'python-openid',
        'pytz',
        'raven',
        'translitcodec',
    ],
    scripts=[
    ],
    dependency_links = [
        'https://github.com/ryanolson/flask-bootstrap/tarball/master#egg=Flask-Bootstrap-2.3.2.12',
        'https://github.com/ryanolson/flask-couchdb-schematics/tarball/master#egg=Flask-CouchDB-Schematics-0.1.0-beta',
    ]
)
