#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
    samplectl
    ~~~~~~~~~

    :copyright: (c) 2013 by Ryan Olson.
    :license: BSD, see LICENSE for more details.
"""
from flask import current_app
from flask.ext.script import Manager

#from clappsample import create_app
#manager = Manager(create_app)

